CREATE TABLE users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255),
    created TIMESTAMP DEFAULT NOW()
);


CREATE TABLE quizScore(
    id INT AUTO_INCREMENT PRIMARY KEY,
    score INT,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);